version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      NEW_RELIC_CONFIG_FILE: newrelic.ini
    volumes:
      - .:/app
    command: ["newrelic-admin", "run-program", "python", "app.py"]
