name: CI/CD with Branch Management

on:
  pull_request:
    branches: [new-branch]
  push:
    branches: [new-branch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest discover tests

  manage-branches:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/new-branch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.name "github-actions[bot]" && git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge new-branch into main branch
        run: |
          git checkout main
          git pull origin main
          git checkout new-branch
          git pull origin new-branch
          git checkout main
          git merge new-branch

      - name: Push changes to GitHub
        run: git push origin main

  push-image:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t docker.io/tadeowassner/devops:latest --push .
