name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Copy newrelic.ini to the app directory
        run: cp newrelic.ini 

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64 -t docker.io/tadeowassner/devops:latest .

      - name: Run New Relic Application
        run: newrelic-admin run-program python /app/app.py

      - name: Login to Docker Hub
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u ${{ env.DOCKER_ID }} --password-stdin

      - name: Push Docker image
        run: docker push docker.io/tadeowassner/devops:latest
